### ISSUE TITLE
The package looks quite interesting, It would help if the sample notebooks were saved with output

### ISSUE THREAD

**Issue by dartdog** [SauceCat/pydqc#1]
Try "save and checkpoint" the notebook after running it,  before commit,, then it will render with output.. It will make it easier for people like me to see if they want to try it out before they have to install it..

**Comment by sosuneko** [comment]
Hi @dartdog, thanks for your advice. Actually, the output notebook is not for data quality reporting, but for easing the further customized checking. You still need to input the data table at the top of the notebook. For sample outputs, you can check the excel files instead.

**Comment by dartdog** [comment]
Having excel as a dependency seems strange...
