### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by prakashtewari** [SauceCat/pydqc#5]
Hi there, 

Thanks for the great package. 
Sorry I am new to Python and trying to pick up. Please see my issue below.

I am seeing there an error everytime I run the command
from pydqc import infer_schema, data_summary, data_compare, data_consist
 
ModuleNotFoundError: No module named 'dqc_utils'

If I make the anaconda3\Lib\site-packages\pydqc-0.1-py3.6.egg\pydqc as my working directory, then I am able run without error. But when I am in a different working directory I get this error.

My Path variable is set to anaconda3\Lib\site-packages. 
I am able to load other packages like numpy, pandas, scipy etc.

Also, I notice that _init_.py file is blank for PyDQC package. Is that supposed to be the case?

Sorry again if this is a beginner's problem.

**Comment by sosuneko** [comment]
hi @prakashtewari,

I think I've fixed the problem for python3. And you can now use `pip install pydqc`
